### ISSUE TITLE
Build fails with the update as of Mar 8th commit in main

### ISSUE THREAD

**Issue by IoTFier** [microsoft/dicom-server#614]
**Describe the bug**
local build of the OSS repo is failing with the following errors  - 
![image](https://user-images.githubusercontent.com/26844611/110399843-2b6eb200-803c-11eb-9df8-63da6c5d74de.png)

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	CA1802	Field 'DicomServerBlobConfigurationSectionName' is declared as 'readonly' but is initialized with a constant value. Mark this field as 'const' instead.	Microsoft.Health.Dicom.Blob	{local path|\dicom-server\src\Microsoft.Health.Dicom.Blob\Registration\DicomServerBuilderBlobRegistrationExtensions.cs	23	Active	A field is declared static and read-only (Shared and ReadOnly in Visual Basic), and is initialized by using a value that is computable at compile time. Because the value that is assigned to the targeted field is computable at compile time, change the declaration to a const (Const in Visual Basic) field so that the value is computed at compile time instead of at run?time.

![image](https://user-images.githubusercontent.com/26844611/110399937-55c06f80-803c-11eb-978b-6a9138aa4929.png)

Your help will be appreciated. Thank you.

**To Reproduce**
1. Update the repo the commit point - bd33cf2 - Refactor Project Files (#606)
2. Build the solution using VS 16.9.0
3. Observer all the errors as outlined in the first screenshot

**Expected behavior**
Solution Build resulting in no errors 

**Actual behavior**
See the attached screenshot above.

**Comment by IoTFier** [comment]
Same error with today's commit : be2a547 - Bump NSubstitute from 4.2.1 to 4.2.2 in /converter/dicom-cast (#624)

**Comment by wsugarman** [comment]
I was able to mostly root cause the issue.

The problem lies in the difference between the .NET SDK in the global.json (5.0103) and the .NET SDK used by the latest Visual Studio (5.0.201). I can build the solution without issue from the command line using `dotnet build`, as can our pipelines. That is because they are using a version of the .NET SDK from the global.json file. However, once I tried updating the SDK, I immediately saw the same errors we both see in Visual Studio. It must mean that the Intellisense is using a newer version of the .NET SDK.

Specifically, it appears the analyzer has gotten cleverer at detecting CA1802 around interpolated strings.

So to fix this issue, I'll put out a PR to fix the VS warnings, and I'll attempt to pin the analyzer warnings to version 5 of the SDK. However, given that VS may use the latest version of the SDK for intellisense, it may not prevent future tooling breaks. I'll investigate what can be done about the intellisense. I can't imagine we're alone in this.

**Comment by IoTFier** [comment]
Hi @wsugarman , I am not sure if that's going to resolve the issue for good.
I was getting the same error even after installing the .Net SDK 5.0.103 to match entry in the global.json.
Is there a setting that needs to set up to route the sdk for build based on certain configuration in the solution / project to override VS settings ?

**Comment by wsugarman** [comment]
I have opened up a separate issue with Visual Studio [here](https://developercommunity.visualstudio.com/t/net-analyzer-using-different-net-sdk-from-globaljs/1363811).
